/* soapWeatherWebServiceSoapProxy.h
   Generated by gSOAP 2.8.99 for weatherService.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapWeatherWebServiceSoapProxy_H
#define soapWeatherWebServiceSoapProxy_H
#include "soapH.h"

    class SOAP_CMAC WeatherWebServiceSoapProxy : public soap {
      public:
        /// Endpoint URL of service 'WeatherWebServiceSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in weatherService.h, if any
        /// Construct a proxy with new managing context
        WeatherWebServiceSoapProxy();
        /// Copy constructor
        WeatherWebServiceSoapProxy(const WeatherWebServiceSoapProxy& rhs);
        /// Construct proxy given a managing context
        WeatherWebServiceSoapProxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        WeatherWebServiceSoapProxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        WeatherWebServiceSoapProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        WeatherWebServiceSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        WeatherWebServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        WeatherWebServiceSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~WeatherWebServiceSoapProxy();
        /// Initializer used by constructors
        virtual void WeatherWebServiceSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual WeatherWebServiceSoapProxy *copy();
        /// Copy assignment
        WeatherWebServiceSoapProxy& operator=(const WeatherWebServiceSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'getSupportCity' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportCity(_ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse) { return this->getSupportCity(NULL, NULL, ns1__getSupportCity, ns1__getSupportCityResponse); }
        /// Web service synchronous operation 'getSupportCity' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportCity(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse) { return this->send_getSupportCity(soap_endpoint_url, soap_action, ns1__getSupportCity) || this->recv_getSupportCity(ns1__getSupportCityResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportCity' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportCity(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity);
        /// Web service asynchronous operation 'recv_getSupportCity' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportCity(_ns1__getSupportCityResponse &ns1__getSupportCityResponse);
        //
        /// Web service synchronous operation 'getSupportProvince' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportProvince(_ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse) { return this->getSupportProvince(NULL, NULL, ns1__getSupportProvince, ns1__getSupportProvinceResponse); }
        /// Web service synchronous operation 'getSupportProvince' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportProvince(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse) { return this->send_getSupportProvince(soap_endpoint_url, soap_action, ns1__getSupportProvince) || this->recv_getSupportProvince(ns1__getSupportProvinceResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportProvince' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportProvince(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince);
        /// Web service asynchronous operation 'recv_getSupportProvince' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportProvince(_ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);
        //
        /// Web service synchronous operation 'getSupportDataSet' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportDataSet(_ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse) { return this->getSupportDataSet(NULL, NULL, ns1__getSupportDataSet, ns1__getSupportDataSetResponse); }
        /// Web service synchronous operation 'getSupportDataSet' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportDataSet(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse) { return this->send_getSupportDataSet(soap_endpoint_url, soap_action, ns1__getSupportDataSet) || this->recv_getSupportDataSet(ns1__getSupportDataSetResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportDataSet' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportDataSet(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet);
        /// Web service asynchronous operation 'recv_getSupportDataSet' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportDataSet(_ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);
        //
        /// Web service synchronous operation 'getWeatherbyCityName' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityName(_ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse) { return this->getWeatherbyCityName(NULL, NULL, ns1__getWeatherbyCityName, ns1__getWeatherbyCityNameResponse); }
        /// Web service synchronous operation 'getWeatherbyCityName' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityName(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse) { return this->send_getWeatherbyCityName(soap_endpoint_url, soap_action, ns1__getWeatherbyCityName) || this->recv_getWeatherbyCityName(ns1__getWeatherbyCityNameResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getWeatherbyCityName' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getWeatherbyCityName(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName);
        /// Web service asynchronous operation 'recv_getWeatherbyCityName' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getWeatherbyCityName(_ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);
        //
        /// Web service synchronous operation 'getWeatherbyCityNamePro' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityNamePro(_ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse) { return this->getWeatherbyCityNamePro(NULL, NULL, ns1__getWeatherbyCityNamePro, ns1__getWeatherbyCityNameProResponse); }
        /// Web service synchronous operation 'getWeatherbyCityNamePro' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityNamePro(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse) { return this->send_getWeatherbyCityNamePro(soap_endpoint_url, soap_action, ns1__getWeatherbyCityNamePro) || this->recv_getWeatherbyCityNamePro(ns1__getWeatherbyCityNameProResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getWeatherbyCityNamePro' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getWeatherbyCityNamePro(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro);
        /// Web service asynchronous operation 'recv_getWeatherbyCityNamePro' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getWeatherbyCityNamePro(_ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);
        //
        /// Web service synchronous operation 'getSupportCity' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportCity_(_ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse) { return this->getSupportCity_(NULL, NULL, ns1__getSupportCity, ns1__getSupportCityResponse); }
        /// Web service synchronous operation 'getSupportCity' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportCity_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity, _ns1__getSupportCityResponse &ns1__getSupportCityResponse) { return this->send_getSupportCity_(soap_endpoint_url, soap_action, ns1__getSupportCity) || this->recv_getSupportCity_(ns1__getSupportCityResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportCity' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportCity_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportCity *ns1__getSupportCity);
        /// Web service asynchronous operation 'recv_getSupportCity' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportCity_(_ns1__getSupportCityResponse &ns1__getSupportCityResponse);
        //
        /// Web service synchronous operation 'getSupportProvince' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportProvince_(_ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse) { return this->getSupportProvince_(NULL, NULL, ns1__getSupportProvince, ns1__getSupportProvinceResponse); }
        /// Web service synchronous operation 'getSupportProvince' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportProvince_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince, _ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse) { return this->send_getSupportProvince_(soap_endpoint_url, soap_action, ns1__getSupportProvince) || this->recv_getSupportProvince_(ns1__getSupportProvinceResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportProvince' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportProvince_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportProvince *ns1__getSupportProvince);
        /// Web service asynchronous operation 'recv_getSupportProvince' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportProvince_(_ns1__getSupportProvinceResponse &ns1__getSupportProvinceResponse);
        //
        /// Web service synchronous operation 'getSupportDataSet' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportDataSet_(_ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse) { return this->getSupportDataSet_(NULL, NULL, ns1__getSupportDataSet, ns1__getSupportDataSetResponse); }
        /// Web service synchronous operation 'getSupportDataSet' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getSupportDataSet_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet, _ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse) { return this->send_getSupportDataSet_(soap_endpoint_url, soap_action, ns1__getSupportDataSet) || this->recv_getSupportDataSet_(ns1__getSupportDataSetResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getSupportDataSet' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getSupportDataSet_(const char *soap_endpoint_url, const char *soap_action, _ns1__getSupportDataSet *ns1__getSupportDataSet);
        /// Web service asynchronous operation 'recv_getSupportDataSet' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getSupportDataSet_(_ns1__getSupportDataSetResponse &ns1__getSupportDataSetResponse);
        //
        /// Web service synchronous operation 'getWeatherbyCityName' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityName_(_ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse) { return this->getWeatherbyCityName_(NULL, NULL, ns1__getWeatherbyCityName, ns1__getWeatherbyCityNameResponse); }
        /// Web service synchronous operation 'getWeatherbyCityName' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityName_(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName, _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse) { return this->send_getWeatherbyCityName_(soap_endpoint_url, soap_action, ns1__getWeatherbyCityName) || this->recv_getWeatherbyCityName_(ns1__getWeatherbyCityNameResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getWeatherbyCityName' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getWeatherbyCityName_(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityName *ns1__getWeatherbyCityName);
        /// Web service asynchronous operation 'recv_getWeatherbyCityName' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getWeatherbyCityName_(_ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse);
        //
        /// Web service synchronous operation 'getWeatherbyCityNamePro' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityNamePro_(_ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse) { return this->getWeatherbyCityNamePro_(NULL, NULL, ns1__getWeatherbyCityNamePro, ns1__getWeatherbyCityNameProResponse); }
        /// Web service synchronous operation 'getWeatherbyCityNamePro' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getWeatherbyCityNamePro_(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro, _ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse) { return this->send_getWeatherbyCityNamePro_(soap_endpoint_url, soap_action, ns1__getWeatherbyCityNamePro) || this->recv_getWeatherbyCityNamePro_(ns1__getWeatherbyCityNameProResponse) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getWeatherbyCityNamePro' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getWeatherbyCityNamePro_(const char *soap_endpoint_url, const char *soap_action, _ns1__getWeatherbyCityNamePro *ns1__getWeatherbyCityNamePro);
        /// Web service asynchronous operation 'recv_getWeatherbyCityNamePro' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getWeatherbyCityNamePro_(_ns1__getWeatherbyCityNameProResponse &ns1__getWeatherbyCityNameProResponse);
    };
#endif
