/* weatherService.h
   Generated by wsdl2h 2.8.99 from http://www.webxml.com.cn/WebServices/WeatherWebService.asmx?wsdl and typemap.dat
   2020-03-22 09:54:02 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on weatherService.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://WebXml.com.cn/                                                    *
 *                                                                            *
\******************************************************************************/

/* WSDL Documentation:

<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>
Web 2.5
340  60 </br>Web
Services<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx"
target="_blank"></a> QQ8409035<br />
WEB http://www.webxml.com.cn/ </strong><br
/><span style="color:#999999;"> WEB 
http://www.onhap.com/WebServices/WeatherWebService.asmx 
http://www.webxml.com.cn/WebServices/WeatherWebService.asmx </span><br
/><br />&nbsp;
*/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER typemap variable:                                               *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://WebXml.com.cn/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://WebXml.com.cn/"
//gsoap ns1   schema namespace:	http://WebXml.com.cn/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Built-in element "xs:schema".
typedef _XML _xsd__schema;


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


class ns1__ArrayOfString;

class _ns1__getSupportCity;

class _ns1__getSupportCityResponse;

class _ns1__getSupportProvince;

class _ns1__getSupportProvinceResponse;

class _ns1__getSupportDataSet;

class _ns1__getSupportDataSetResponse;

class _ns1__getWeatherbyCityName;

class _ns1__getWeatherbyCityNameResponse;

class _ns1__getWeatherbyCityNamePro;

class _ns1__getWeatherbyCityNameProResponse;

class _ns1__DataSet;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://WebXml.com.cn/                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://WebXml.com.cn/                                                    *
 *                                                                            *
\******************************************************************************/

/// @brief "http://WebXml.com.cn/":ArrayOfString is a complexType.
///
/// @note class ns1__ArrayOfString operations:
/// - ns1__ArrayOfString* soap_new_ns1__ArrayOfString(soap*) allocate and default initialize
/// - ns1__ArrayOfString* soap_new_ns1__ArrayOfString(soap*, int num) allocate and default initialize an array
/// - ns1__ArrayOfString* soap_new_req_ns1__ArrayOfString(soap*, ...) allocate, set required members
/// - ns1__ArrayOfString* soap_new_set_ns1__ArrayOfString(soap*, ...) allocate, set all public members
/// - ns1__ArrayOfString::soap_default(soap*) default initialize members
/// - int soap_read_ns1__ArrayOfString(soap*, ns1__ArrayOfString*) deserialize from a stream
/// - int soap_write_ns1__ArrayOfString(soap*, ns1__ArrayOfString*) serialize to a stream
/// - ns1__ArrayOfString* ns1__ArrayOfString::soap_dup(soap*) returns deep copy of ns1__ArrayOfString, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__ArrayOfString::soap_del() deep deletes ns1__ArrayOfString data members, use only after ns1__ArrayOfString::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int ns1__ArrayOfString::soap_type() returns SOAP_TYPE_ns1__ArrayOfString or derived type identifier
class ns1__ArrayOfString
{ public:
/// Vector of std::string of length 0..unbounded.
    std::vector<std::string            > string                         0;	///< Multiple elements.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportCity
/// @brief "http://WebXml.com.cn/":getSupportCity is a complexType.
///
/// @note class _ns1__getSupportCity operations:
/// - _ns1__getSupportCity* soap_new__ns1__getSupportCity(soap*) allocate and default initialize
/// - _ns1__getSupportCity* soap_new__ns1__getSupportCity(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportCity* soap_new_req__ns1__getSupportCity(soap*, ...) allocate, set required members
/// - _ns1__getSupportCity* soap_new_set__ns1__getSupportCity(soap*, ...) allocate, set all public members
/// - _ns1__getSupportCity::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportCity(soap*, _ns1__getSupportCity*) deserialize from a stream
/// - int soap_write__ns1__getSupportCity(soap*, _ns1__getSupportCity*) serialize to a stream
/// - _ns1__getSupportCity* _ns1__getSupportCity::soap_dup(soap*) returns deep copy of _ns1__getSupportCity, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportCity::soap_del() deep deletes _ns1__getSupportCity data members, use only after _ns1__getSupportCity::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportCity::soap_type() returns SOAP_TYPE__ns1__getSupportCity or derived type identifier
class _ns1__getSupportCity
{ public:
/// Element "byProvinceName" of type xs:string.
    std::string*                         byProvinceName                 0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportCityResponse
/// @brief "http://WebXml.com.cn/":getSupportCityResponse is a complexType.
///
/// @note class _ns1__getSupportCityResponse operations:
/// - _ns1__getSupportCityResponse* soap_new__ns1__getSupportCityResponse(soap*) allocate and default initialize
/// - _ns1__getSupportCityResponse* soap_new__ns1__getSupportCityResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportCityResponse* soap_new_req__ns1__getSupportCityResponse(soap*, ...) allocate, set required members
/// - _ns1__getSupportCityResponse* soap_new_set__ns1__getSupportCityResponse(soap*, ...) allocate, set all public members
/// - _ns1__getSupportCityResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportCityResponse(soap*, _ns1__getSupportCityResponse*) deserialize from a stream
/// - int soap_write__ns1__getSupportCityResponse(soap*, _ns1__getSupportCityResponse*) serialize to a stream
/// - _ns1__getSupportCityResponse* _ns1__getSupportCityResponse::soap_dup(soap*) returns deep copy of _ns1__getSupportCityResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportCityResponse::soap_del() deep deletes _ns1__getSupportCityResponse data members, use only after _ns1__getSupportCityResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportCityResponse::soap_type() returns SOAP_TYPE__ns1__getSupportCityResponse or derived type identifier
class _ns1__getSupportCityResponse
{ public:
/// Element "getSupportCityResult" of type "http://WebXml.com.cn/":ArrayOfString.
    ns1__ArrayOfString*                  getSupportCityResult           0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportProvince
/// @brief "http://WebXml.com.cn/":getSupportProvince is a complexType.
///
/// @note class _ns1__getSupportProvince operations:
/// - _ns1__getSupportProvince* soap_new__ns1__getSupportProvince(soap*) allocate and default initialize
/// - _ns1__getSupportProvince* soap_new__ns1__getSupportProvince(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportProvince* soap_new_req__ns1__getSupportProvince(soap*, ...) allocate, set required members
/// - _ns1__getSupportProvince* soap_new_set__ns1__getSupportProvince(soap*, ...) allocate, set all public members
/// - _ns1__getSupportProvince::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportProvince(soap*, _ns1__getSupportProvince*) deserialize from a stream
/// - int soap_write__ns1__getSupportProvince(soap*, _ns1__getSupportProvince*) serialize to a stream
/// - _ns1__getSupportProvince* _ns1__getSupportProvince::soap_dup(soap*) returns deep copy of _ns1__getSupportProvince, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportProvince::soap_del() deep deletes _ns1__getSupportProvince data members, use only after _ns1__getSupportProvince::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportProvince::soap_type() returns SOAP_TYPE__ns1__getSupportProvince or derived type identifier
class _ns1__getSupportProvince
{ public:
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportProvinceResponse
/// @brief "http://WebXml.com.cn/":getSupportProvinceResponse is a complexType.
///
/// @note class _ns1__getSupportProvinceResponse operations:
/// - _ns1__getSupportProvinceResponse* soap_new__ns1__getSupportProvinceResponse(soap*) allocate and default initialize
/// - _ns1__getSupportProvinceResponse* soap_new__ns1__getSupportProvinceResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportProvinceResponse* soap_new_req__ns1__getSupportProvinceResponse(soap*, ...) allocate, set required members
/// - _ns1__getSupportProvinceResponse* soap_new_set__ns1__getSupportProvinceResponse(soap*, ...) allocate, set all public members
/// - _ns1__getSupportProvinceResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportProvinceResponse(soap*, _ns1__getSupportProvinceResponse*) deserialize from a stream
/// - int soap_write__ns1__getSupportProvinceResponse(soap*, _ns1__getSupportProvinceResponse*) serialize to a stream
/// - _ns1__getSupportProvinceResponse* _ns1__getSupportProvinceResponse::soap_dup(soap*) returns deep copy of _ns1__getSupportProvinceResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportProvinceResponse::soap_del() deep deletes _ns1__getSupportProvinceResponse data members, use only after _ns1__getSupportProvinceResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportProvinceResponse::soap_type() returns SOAP_TYPE__ns1__getSupportProvinceResponse or derived type identifier
class _ns1__getSupportProvinceResponse
{ public:
/// Element "getSupportProvinceResult" of type "http://WebXml.com.cn/":ArrayOfString.
    ns1__ArrayOfString*                  getSupportProvinceResult       0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportDataSet
/// @brief "http://WebXml.com.cn/":getSupportDataSet is a complexType.
///
/// @note class _ns1__getSupportDataSet operations:
/// - _ns1__getSupportDataSet* soap_new__ns1__getSupportDataSet(soap*) allocate and default initialize
/// - _ns1__getSupportDataSet* soap_new__ns1__getSupportDataSet(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportDataSet* soap_new_req__ns1__getSupportDataSet(soap*, ...) allocate, set required members
/// - _ns1__getSupportDataSet* soap_new_set__ns1__getSupportDataSet(soap*, ...) allocate, set all public members
/// - _ns1__getSupportDataSet::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportDataSet(soap*, _ns1__getSupportDataSet*) deserialize from a stream
/// - int soap_write__ns1__getSupportDataSet(soap*, _ns1__getSupportDataSet*) serialize to a stream
/// - _ns1__getSupportDataSet* _ns1__getSupportDataSet::soap_dup(soap*) returns deep copy of _ns1__getSupportDataSet, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportDataSet::soap_del() deep deletes _ns1__getSupportDataSet data members, use only after _ns1__getSupportDataSet::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportDataSet::soap_type() returns SOAP_TYPE__ns1__getSupportDataSet or derived type identifier
class _ns1__getSupportDataSet
{ public:
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getSupportDataSetResponse
/// @brief "http://WebXml.com.cn/":getSupportDataSetResponse is a complexType.
///
/// @note class _ns1__getSupportDataSetResponse operations:
/// - _ns1__getSupportDataSetResponse* soap_new__ns1__getSupportDataSetResponse(soap*) allocate and default initialize
/// - _ns1__getSupportDataSetResponse* soap_new__ns1__getSupportDataSetResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportDataSetResponse* soap_new_req__ns1__getSupportDataSetResponse(soap*, ...) allocate, set required members
/// - _ns1__getSupportDataSetResponse* soap_new_set__ns1__getSupportDataSetResponse(soap*, ...) allocate, set all public members
/// - _ns1__getSupportDataSetResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportDataSetResponse(soap*, _ns1__getSupportDataSetResponse*) deserialize from a stream
/// - int soap_write__ns1__getSupportDataSetResponse(soap*, _ns1__getSupportDataSetResponse*) serialize to a stream
/// - _ns1__getSupportDataSetResponse* _ns1__getSupportDataSetResponse::soap_dup(soap*) returns deep copy of _ns1__getSupportDataSetResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportDataSetResponse::soap_del() deep deletes _ns1__getSupportDataSetResponse data members, use only after _ns1__getSupportDataSetResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportDataSetResponse::soap_type() returns SOAP_TYPE__ns1__getSupportDataSetResponse or derived type identifier
class _ns1__getSupportDataSetResponse
{ public:
/// @note class _ns1__getSupportDataSetResponse_getSupportDataSetResult operations:
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult* soap_new__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*) allocate and default initialize
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult* soap_new__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*, int num) allocate and default initialize an array
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult* soap_new_req__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*, ...) allocate, set required members
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult* soap_new_set__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*, ...) allocate, set all public members
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult*) deserialize from a stream
/// - int soap_write__ns1__getSupportDataSetResponse_getSupportDataSetResult(soap*, _ns1__getSupportDataSetResponse_getSupportDataSetResult*) serialize to a stream
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult* _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_dup(soap*) returns deep copy of _ns1__getSupportDataSetResponse_getSupportDataSetResult, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_del() deep deletes _ns1__getSupportDataSetResponse_getSupportDataSetResult data members, use only after _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getSupportDataSetResponse_getSupportDataSetResult::soap_type() returns SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult or derived type identifier
    class _ns1__getSupportDataSetResponse_getSupportDataSetResult
    { public:
/// Imported element reference xs:schema.
    _xsd__schema                         xsd__schema                    1;	///< Required element.
/// <any namespace="##any">
/// @note Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d for xsd__anyType DOM (soap_dom_element):
///       wsdl2h maps xsd:any to xsd__anyType, use typemap.dat to remap.
    _XML                                 __any                         0;	///< Store any element content in XML string.
    }                                   *getSupportDataSetResult        0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getWeatherbyCityName
/// @brief "http://WebXml.com.cn/":getWeatherbyCityName is a complexType.
///
/// @note class _ns1__getWeatherbyCityName operations:
/// - _ns1__getWeatherbyCityName* soap_new__ns1__getWeatherbyCityName(soap*) allocate and default initialize
/// - _ns1__getWeatherbyCityName* soap_new__ns1__getWeatherbyCityName(soap*, int num) allocate and default initialize an array
/// - _ns1__getWeatherbyCityName* soap_new_req__ns1__getWeatherbyCityName(soap*, ...) allocate, set required members
/// - _ns1__getWeatherbyCityName* soap_new_set__ns1__getWeatherbyCityName(soap*, ...) allocate, set all public members
/// - _ns1__getWeatherbyCityName::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getWeatherbyCityName(soap*, _ns1__getWeatherbyCityName*) deserialize from a stream
/// - int soap_write__ns1__getWeatherbyCityName(soap*, _ns1__getWeatherbyCityName*) serialize to a stream
/// - _ns1__getWeatherbyCityName* _ns1__getWeatherbyCityName::soap_dup(soap*) returns deep copy of _ns1__getWeatherbyCityName, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getWeatherbyCityName::soap_del() deep deletes _ns1__getWeatherbyCityName data members, use only after _ns1__getWeatherbyCityName::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getWeatherbyCityName::soap_type() returns SOAP_TYPE__ns1__getWeatherbyCityName or derived type identifier
class _ns1__getWeatherbyCityName
{ public:
/// Element "theCityName" of type xs:string.
    std::string*                         theCityName                    0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getWeatherbyCityNameResponse
/// @brief "http://WebXml.com.cn/":getWeatherbyCityNameResponse is a complexType.
///
/// @note class _ns1__getWeatherbyCityNameResponse operations:
/// - _ns1__getWeatherbyCityNameResponse* soap_new__ns1__getWeatherbyCityNameResponse(soap*) allocate and default initialize
/// - _ns1__getWeatherbyCityNameResponse* soap_new__ns1__getWeatherbyCityNameResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__getWeatherbyCityNameResponse* soap_new_req__ns1__getWeatherbyCityNameResponse(soap*, ...) allocate, set required members
/// - _ns1__getWeatherbyCityNameResponse* soap_new_set__ns1__getWeatherbyCityNameResponse(soap*, ...) allocate, set all public members
/// - _ns1__getWeatherbyCityNameResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getWeatherbyCityNameResponse(soap*, _ns1__getWeatherbyCityNameResponse*) deserialize from a stream
/// - int soap_write__ns1__getWeatherbyCityNameResponse(soap*, _ns1__getWeatherbyCityNameResponse*) serialize to a stream
/// - _ns1__getWeatherbyCityNameResponse* _ns1__getWeatherbyCityNameResponse::soap_dup(soap*) returns deep copy of _ns1__getWeatherbyCityNameResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getWeatherbyCityNameResponse::soap_del() deep deletes _ns1__getWeatherbyCityNameResponse data members, use only after _ns1__getWeatherbyCityNameResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getWeatherbyCityNameResponse::soap_type() returns SOAP_TYPE__ns1__getWeatherbyCityNameResponse or derived type identifier
class _ns1__getWeatherbyCityNameResponse
{ public:
/// Element "getWeatherbyCityNameResult" of type "http://WebXml.com.cn/":ArrayOfString.
    ns1__ArrayOfString*                  getWeatherbyCityNameResult     0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getWeatherbyCityNamePro
/// @brief "http://WebXml.com.cn/":getWeatherbyCityNamePro is a complexType.
///
/// @note class _ns1__getWeatherbyCityNamePro operations:
/// - _ns1__getWeatherbyCityNamePro* soap_new__ns1__getWeatherbyCityNamePro(soap*) allocate and default initialize
/// - _ns1__getWeatherbyCityNamePro* soap_new__ns1__getWeatherbyCityNamePro(soap*, int num) allocate and default initialize an array
/// - _ns1__getWeatherbyCityNamePro* soap_new_req__ns1__getWeatherbyCityNamePro(soap*, ...) allocate, set required members
/// - _ns1__getWeatherbyCityNamePro* soap_new_set__ns1__getWeatherbyCityNamePro(soap*, ...) allocate, set all public members
/// - _ns1__getWeatherbyCityNamePro::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getWeatherbyCityNamePro(soap*, _ns1__getWeatherbyCityNamePro*) deserialize from a stream
/// - int soap_write__ns1__getWeatherbyCityNamePro(soap*, _ns1__getWeatherbyCityNamePro*) serialize to a stream
/// - _ns1__getWeatherbyCityNamePro* _ns1__getWeatherbyCityNamePro::soap_dup(soap*) returns deep copy of _ns1__getWeatherbyCityNamePro, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getWeatherbyCityNamePro::soap_del() deep deletes _ns1__getWeatherbyCityNamePro data members, use only after _ns1__getWeatherbyCityNamePro::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getWeatherbyCityNamePro::soap_type() returns SOAP_TYPE__ns1__getWeatherbyCityNamePro or derived type identifier
class _ns1__getWeatherbyCityNamePro
{ public:
/// Element "theCityName" of type xs:string.
    std::string*                         theCityName                    0;	///< Optional element.
/// Element "theUserID" of type xs:string.
    std::string*                         theUserID                      0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":getWeatherbyCityNameProResponse
/// @brief "http://WebXml.com.cn/":getWeatherbyCityNameProResponse is a complexType.
///
/// @note class _ns1__getWeatherbyCityNameProResponse operations:
/// - _ns1__getWeatherbyCityNameProResponse* soap_new__ns1__getWeatherbyCityNameProResponse(soap*) allocate and default initialize
/// - _ns1__getWeatherbyCityNameProResponse* soap_new__ns1__getWeatherbyCityNameProResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__getWeatherbyCityNameProResponse* soap_new_req__ns1__getWeatherbyCityNameProResponse(soap*, ...) allocate, set required members
/// - _ns1__getWeatherbyCityNameProResponse* soap_new_set__ns1__getWeatherbyCityNameProResponse(soap*, ...) allocate, set all public members
/// - _ns1__getWeatherbyCityNameProResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getWeatherbyCityNameProResponse(soap*, _ns1__getWeatherbyCityNameProResponse*) deserialize from a stream
/// - int soap_write__ns1__getWeatherbyCityNameProResponse(soap*, _ns1__getWeatherbyCityNameProResponse*) serialize to a stream
/// - _ns1__getWeatherbyCityNameProResponse* _ns1__getWeatherbyCityNameProResponse::soap_dup(soap*) returns deep copy of _ns1__getWeatherbyCityNameProResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getWeatherbyCityNameProResponse::soap_del() deep deletes _ns1__getWeatherbyCityNameProResponse data members, use only after _ns1__getWeatherbyCityNameProResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__getWeatherbyCityNameProResponse::soap_type() returns SOAP_TYPE__ns1__getWeatherbyCityNameProResponse or derived type identifier
class _ns1__getWeatherbyCityNameProResponse
{ public:
/// Element "getWeatherbyCityNameProResult" of type "http://WebXml.com.cn/":ArrayOfString.
    ns1__ArrayOfString*                  getWeatherbyCityNameProResult  0;	///< Optional element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://WebXml.com.cn/":DataSet
/// @brief "http://WebXml.com.cn/":DataSet is a complexType.
///
/// @note class _ns1__DataSet operations:
/// - _ns1__DataSet* soap_new__ns1__DataSet(soap*) allocate and default initialize
/// - _ns1__DataSet* soap_new__ns1__DataSet(soap*, int num) allocate and default initialize an array
/// - _ns1__DataSet* soap_new_req__ns1__DataSet(soap*, ...) allocate, set required members
/// - _ns1__DataSet* soap_new_set__ns1__DataSet(soap*, ...) allocate, set all public members
/// - _ns1__DataSet::soap_default(soap*) default initialize members
/// - int soap_read__ns1__DataSet(soap*, _ns1__DataSet*) deserialize from a stream
/// - int soap_write__ns1__DataSet(soap*, _ns1__DataSet*) serialize to a stream
/// - _ns1__DataSet* _ns1__DataSet::soap_dup(soap*) returns deep copy of _ns1__DataSet, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__DataSet::soap_del() deep deletes _ns1__DataSet data members, use only after _ns1__DataSet::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__DataSet::soap_type() returns SOAP_TYPE__ns1__DataSet or derived type identifier
class _ns1__DataSet
{ public:
/// Imported element reference xs:schema.
    _xsd__schema                         xsd__schema                    1;	///< Required element.
/// <any namespace="##any">
/// @note Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d for xsd__anyType DOM (soap_dom_element):
///       wsdl2h maps xsd:any to xsd__anyType, use typemap.dat to remap.
    _XML                                 __any                         0;	///< Store any element content in XML string.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://WebXml.com.cn/                                                    *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://WebXml.com.cn/":ArrayOfString of type "http://WebXml.com.cn/":ArrayOfString.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://WebXml.com.cn/                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	WeatherWebServiceSoap 
//gsoap ns1  service type:	WeatherWebServiceSoap 
//gsoap ns1  service port:	http://www.webxml.com.cn/WebServices/WeatherWebService.asmx 
//gsoap ns1  service namespace:	http://WebXml.com.cn/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_documentation Documentation
<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>
Web 2.5
340  60 </br>Web
Services<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx"
target="_blank"></a> QQ8409035<br />
WEB http://www.webxml.com.cn/ </strong><br
/><span style="color:#999999;"> WEB 
http://www.onhap.com/WebServices/WeatherWebService.asmx 
http://www.webxml.com.cn/WebServices/WeatherWebService.asmx </span><br
/><br />&nbsp;

@section Service_bindings Service Bindings

  - @ref WeatherWebServiceSoap

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page WeatherWebServiceSoap Binding "WeatherWebServiceSoap"

@section WeatherWebServiceSoap_service Service Documentation "WeatherWebServiceSoap"
<a href="http://www.webxml.com.cn/" target="_blank">WebXml.com.cn</a> <strong>
Web 2.5
340  60 </br>Web
Services<a href="http://www.webxml.com.cn/zh_cn/contact_us.aspx"
target="_blank"></a> QQ8409035<br />
WEB http://www.webxml.com.cn/ </strong><br
/><span style="color:#999999;"> WEB 
http://www.onhap.com/WebServices/WeatherWebService.asmx 
http://www.webxml.com.cn/WebServices/WeatherWebService.asmx </span><br
/><br />&nbsp;

@section WeatherWebServiceSoap_operations Operations of Binding "WeatherWebServiceSoap"

  - @ref __ns1__getSupportCity

  - @ref __ns1__getSupportProvince

  - @ref __ns1__getSupportDataSet

  - @ref __ns1__getWeatherbyCityName

  - @ref __ns1__getWeatherbyCityNamePro

  - @ref __ns1__getSupportCity_

  - @ref __ns1__getSupportProvince_

  - @ref __ns1__getSupportDataSet_

  - @ref __ns1__getWeatherbyCityName_

  - @ref __ns1__getWeatherbyCityNamePro_

@section WeatherWebServiceSoap_ports Default endpoints of Binding "WeatherWebServiceSoap"

  - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   WeatherWebServiceSoap                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportCity                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportCity" of service binding "WeatherWebServiceSoap".
<br /><h3>Web Services</h3><p>byProvinceName
= ALL
String()()</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportCity"

  - Addressing input action: "http://WebXml.com.cn/getSupportCity"

  - Addressing output action: "http://WebXml.com.cn/getSupportCityResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportCity(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportCity*               ns1__getSupportCity,
    // output parameters:
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportCity(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportCity*               ns1__getSupportCity,
    // output parameters:
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportCity SOAP
//gsoap ns1  service method-style:	getSupportCity document
//gsoap ns1  service method-encoding:	getSupportCity literal
//gsoap ns1  service method-input-action:	getSupportCity http://WebXml.com.cn/getSupportCity
//gsoap ns1  service method-output-action:	getSupportCity http://WebXml.com.cn/getSupportCityResponse
int __ns1__getSupportCity(
    _ns1__getSupportCity*               ns1__getSupportCity,	///< Input parameter
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportProvince                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportProvince" of service binding "WeatherWebServiceSoap".
<br /><h3>Web Services</h3><p>
 String()</p><br
/>

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportProvince"

  - Addressing input action: "http://WebXml.com.cn/getSupportProvince"

  - Addressing output action: "http://WebXml.com.cn/getSupportProvinceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportProvince(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportProvince*           ns1__getSupportProvince,
    // output parameters:
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportProvince(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportProvince*           ns1__getSupportProvince,
    // output parameters:
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportProvince SOAP
//gsoap ns1  service method-style:	getSupportProvince document
//gsoap ns1  service method-encoding:	getSupportProvince literal
//gsoap ns1  service method-input-action:	getSupportProvince http://WebXml.com.cn/getSupportProvince
//gsoap ns1  service method-output-action:	getSupportProvince http://WebXml.com.cn/getSupportProvinceResponse
int __ns1__getSupportProvince(
    _ns1__getSupportProvince*           ns1__getSupportProvince,	///< Input parameter
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportDataSet                                                 *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportDataSet" of service binding "WeatherWebServiceSoap".
<br><h3>Web Services</h3><p>DataSet
DataSet.Tables(0) DataSet.Tables(1) DataSet.Tables(0).Rows(i).Item("ID")
 DataSet.Tables(1).Rows(i).Item("ZoneID") <br />Tables(0)ID
= IDZone = Tables(1)ID ZoneID = Tables(0)IDArea
= AreaCode = </p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportDataSet"

  - Addressing input action: "http://WebXml.com.cn/getSupportDataSet"

  - Addressing output action: "http://WebXml.com.cn/getSupportDataSetResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportDataSet(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,
    // output parameters:
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportDataSet(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,
    // output parameters:
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportDataSet SOAP
//gsoap ns1  service method-style:	getSupportDataSet document
//gsoap ns1  service method-encoding:	getSupportDataSet literal
//gsoap ns1  service method-input-action:	getSupportDataSet http://WebXml.com.cn/getSupportDataSet
//gsoap ns1  service method-output-action:	getSupportDataSet http://WebXml.com.cn/getSupportDataSetResponse
int __ns1__getSupportDataSet(
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,	///< Input parameter
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getWeatherbyCityName                                              *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getWeatherbyCityName" of service binding "WeatherWebServiceSoap".
<br><h3></h3><p>theCityName
= ()()
 58367( getSupportCity
 getSupportDataSet )  String(22)23<br
/>String(0)  String(4)String(5)
 String(11) ()()String(12)
 String(16) String(17)
 String(21) String(22)
 <br /><a href="http://www.webxml.com.cn/images/weather.zip"><img
src="http://www.webxml.com.cn/images/download_w.gif" border="0" align="absbottom"
/></a>() <a href="http://www.webxml.com.cn/zh_cn/weather_icon.aspx"
target="_blank"></a> <a href="http://www.webxml.com.cn/files/weather_eg.zip">Web
Services</a> (VB ASP.net 2.0)</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getWeatherbyCityName"

  - Addressing input action: "http://WebXml.com.cn/getWeatherbyCityName"

  - Addressing output action: "http://WebXml.com.cn/getWeatherbyCityNameResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getWeatherbyCityName(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,
    // output parameters:
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getWeatherbyCityName(
    struct soap *soap,
    // input parameters:
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,
    // output parameters:
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getWeatherbyCityName SOAP
//gsoap ns1  service method-style:	getWeatherbyCityName document
//gsoap ns1  service method-encoding:	getWeatherbyCityName literal
//gsoap ns1  service method-input-action:	getWeatherbyCityName http://WebXml.com.cn/getWeatherbyCityName
//gsoap ns1  service method-output-action:	getWeatherbyCityName http://WebXml.com.cn/getWeatherbyCityNameResponse
int __ns1__getWeatherbyCityName(
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,	///< Input parameter
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getWeatherbyCityNamePro                                           *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getWeatherbyCityNamePro" of service binding "WeatherWebServiceSoap".
<br><h3>For</h3><p>
getWeatherbyCityNametheUserID = ID</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getWeatherbyCityNamePro"

  - Addressing input action: "http://WebXml.com.cn/getWeatherbyCityNamePro"

  - Addressing output action: "http://WebXml.com.cn/getWeatherbyCityNameProResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getWeatherbyCityNamePro(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,
    // output parameters:
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getWeatherbyCityNamePro(
    struct soap *soap,
    // input parameters:
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,
    // output parameters:
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getWeatherbyCityNamePro SOAP
//gsoap ns1  service method-style:	getWeatherbyCityNamePro document
//gsoap ns1  service method-encoding:	getWeatherbyCityNamePro literal
//gsoap ns1  service method-input-action:	getWeatherbyCityNamePro http://WebXml.com.cn/getWeatherbyCityNamePro
//gsoap ns1  service method-output-action:	getWeatherbyCityNamePro http://WebXml.com.cn/getWeatherbyCityNameProResponse
int __ns1__getWeatherbyCityNamePro(
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,	///< Input parameter
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportCity_                                                   *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportCity_" of service binding "WeatherWebServiceSoap".
<br /><h3>Web Services</h3><p>byProvinceName
= ALL
String()()</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportCity"

  - Addressing input action: "http://WebXml.com.cn/getSupportCity"

  - Addressing output action: "http://WebXml.com.cn/getSupportCityResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportCity_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportCity*               ns1__getSupportCity,
    // output parameters:
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportCity_(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportCity*               ns1__getSupportCity,
    // output parameters:
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportCity_ SOAP
//gsoap ns1  service method-style:	getSupportCity_ document
//gsoap ns1  service method-encoding:	getSupportCity_ literal
//gsoap ns1  service method-input-action:	getSupportCity_ http://WebXml.com.cn/getSupportCity
//gsoap ns1  service method-output-action:	getSupportCity_ http://WebXml.com.cn/getSupportCityResponse
int __ns1__getSupportCity_(
    _ns1__getSupportCity*               ns1__getSupportCity,	///< Input parameter
    _ns1__getSupportCityResponse       &ns1__getSupportCityResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportProvince_                                               *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportProvince_" of service binding "WeatherWebServiceSoap".
<br /><h3>Web Services</h3><p>
 String()</p><br
/>

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportProvince"

  - Addressing input action: "http://WebXml.com.cn/getSupportProvince"

  - Addressing output action: "http://WebXml.com.cn/getSupportProvinceResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportProvince_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportProvince*           ns1__getSupportProvince,
    // output parameters:
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportProvince_(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportProvince*           ns1__getSupportProvince,
    // output parameters:
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportProvince_ SOAP
//gsoap ns1  service method-style:	getSupportProvince_ document
//gsoap ns1  service method-encoding:	getSupportProvince_ literal
//gsoap ns1  service method-input-action:	getSupportProvince_ http://WebXml.com.cn/getSupportProvince
//gsoap ns1  service method-output-action:	getSupportProvince_ http://WebXml.com.cn/getSupportProvinceResponse
int __ns1__getSupportProvince_(
    _ns1__getSupportProvince*           ns1__getSupportProvince,	///< Input parameter
    _ns1__getSupportProvinceResponse   &ns1__getSupportProvinceResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSupportDataSet_                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSupportDataSet_" of service binding "WeatherWebServiceSoap".
<br><h3>Web Services</h3><p>DataSet
DataSet.Tables(0) DataSet.Tables(1) DataSet.Tables(0).Rows(i).Item("ID")
 DataSet.Tables(1).Rows(i).Item("ZoneID") <br />Tables(0)ID
= IDZone = Tables(1)ID ZoneID = Tables(0)IDArea
= AreaCode = </p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getSupportDataSet"

  - Addressing input action: "http://WebXml.com.cn/getSupportDataSet"

  - Addressing output action: "http://WebXml.com.cn/getSupportDataSetResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSupportDataSet_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,
    // output parameters:
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSupportDataSet_(
    struct soap *soap,
    // input parameters:
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,
    // output parameters:
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSupportDataSet_ SOAP
//gsoap ns1  service method-style:	getSupportDataSet_ document
//gsoap ns1  service method-encoding:	getSupportDataSet_ literal
//gsoap ns1  service method-input-action:	getSupportDataSet_ http://WebXml.com.cn/getSupportDataSet
//gsoap ns1  service method-output-action:	getSupportDataSet_ http://WebXml.com.cn/getSupportDataSetResponse
int __ns1__getSupportDataSet_(
    _ns1__getSupportDataSet*            ns1__getSupportDataSet,	///< Input parameter
    _ns1__getSupportDataSetResponse    &ns1__getSupportDataSetResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getWeatherbyCityName_                                             *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getWeatherbyCityName_" of service binding "WeatherWebServiceSoap".
<br><h3></h3><p>theCityName
= ()()
 58367( getSupportCity
 getSupportDataSet )  String(22)23<br
/>String(0)  String(4)String(5)
 String(11) ()()String(12)
 String(16) String(17)
 String(21) String(22)
 <br /><a href="http://www.webxml.com.cn/images/weather.zip"><img
src="http://www.webxml.com.cn/images/download_w.gif" border="0" align="absbottom"
/></a>() <a href="http://www.webxml.com.cn/zh_cn/weather_icon.aspx"
target="_blank"></a> <a href="http://www.webxml.com.cn/files/weather_eg.zip">Web
Services</a> (VB ASP.net 2.0)</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getWeatherbyCityName"

  - Addressing input action: "http://WebXml.com.cn/getWeatherbyCityName"

  - Addressing output action: "http://WebXml.com.cn/getWeatherbyCityNameResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getWeatherbyCityName_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,
    // output parameters:
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getWeatherbyCityName_(
    struct soap *soap,
    // input parameters:
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,
    // output parameters:
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getWeatherbyCityName_ SOAP
//gsoap ns1  service method-style:	getWeatherbyCityName_ document
//gsoap ns1  service method-encoding:	getWeatherbyCityName_ literal
//gsoap ns1  service method-input-action:	getWeatherbyCityName_ http://WebXml.com.cn/getWeatherbyCityName
//gsoap ns1  service method-output-action:	getWeatherbyCityName_ http://WebXml.com.cn/getWeatherbyCityNameResponse
int __ns1__getWeatherbyCityName_(
    _ns1__getWeatherbyCityName*         ns1__getWeatherbyCityName,	///< Input parameter
    _ns1__getWeatherbyCityNameResponse &ns1__getWeatherbyCityNameResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getWeatherbyCityNamePro_                                          *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getWeatherbyCityNamePro_" of service binding "WeatherWebServiceSoap".
<br><h3>For</h3><p>
getWeatherbyCityNametheUserID = ID</p><br />

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://www.webxml.com.cn/WebServices/WeatherWebService.asmx

  - Default SOAP action or REST location path:
    - "http://WebXml.com.cn/getWeatherbyCityNamePro"

  - Addressing input action: "http://WebXml.com.cn/getWeatherbyCityNamePro"

  - Addressing output action: "http://WebXml.com.cn/getWeatherbyCityNameProResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getWeatherbyCityNamePro_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,
    // output parameters:
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getWeatherbyCityNamePro_(
    struct soap *soap,
    // input parameters:
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,
    // output parameters:
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse
  );
@endcode

C++ proxy class (defined in soapWeatherWebServiceSoapProxy.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapWeatherWebServiceSoapService.h generated with soapcpp2):
@code
  class WeatherWebServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getWeatherbyCityNamePro_ SOAP
//gsoap ns1  service method-style:	getWeatherbyCityNamePro_ document
//gsoap ns1  service method-encoding:	getWeatherbyCityNamePro_ literal
//gsoap ns1  service method-input-action:	getWeatherbyCityNamePro_ http://WebXml.com.cn/getWeatherbyCityNamePro
//gsoap ns1  service method-output-action:	getWeatherbyCityNamePro_ http://WebXml.com.cn/getWeatherbyCityNameProResponse
int __ns1__getWeatherbyCityNamePro_(
    _ns1__getWeatherbyCityNamePro*      ns1__getWeatherbyCityNamePro,	///< Input parameter
    _ns1__getWeatherbyCityNameProResponse&ns1__getWeatherbyCityNameProResponse	///< Output parameter
);

/** @page WeatherWebServiceSoap Binding "WeatherWebServiceSoap"

@section WeatherWebServiceSoap_policy_enablers Policy Enablers of Binding "WeatherWebServiceSoap"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://WebXml.com.cn/"

  - <ns1:getSupportCity> @ref _ns1__getSupportCity
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportCity(struct soap*, _ns1__getSupportCity*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportCity(struct soap*, _ns1__getSupportCity*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportCity(struct soap*, const char *URL, _ns1__getSupportCity*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportCity(struct soap*, const char *URL, _ns1__getSupportCity*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportCity(struct soap*, const char *URL, _ns1__getSupportCity*);
    soap_POST_recv__ns1__getSupportCity(struct soap*, _ns1__getSupportCity*);
    @endcode

  - <ns1:getSupportCityResponse> @ref _ns1__getSupportCityResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportCityResponse(struct soap*, const char *URL, _ns1__getSupportCityResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportCityResponse(struct soap*, const char *URL, _ns1__getSupportCityResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportCityResponse(struct soap*, const char *URL, _ns1__getSupportCityResponse*);
    soap_POST_recv__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse*);
    @endcode

  - <ns1:getSupportProvince> @ref _ns1__getSupportProvince
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportProvince(struct soap*, const char *URL, _ns1__getSupportProvince*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportProvince(struct soap*, const char *URL, _ns1__getSupportProvince*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportProvince(struct soap*, const char *URL, _ns1__getSupportProvince*);
    soap_POST_recv__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince*);
    @endcode

  - <ns1:getSupportProvinceResponse> @ref _ns1__getSupportProvinceResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportProvinceResponse(struct soap*, const char *URL, _ns1__getSupportProvinceResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportProvinceResponse(struct soap*, const char *URL, _ns1__getSupportProvinceResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportProvinceResponse(struct soap*, const char *URL, _ns1__getSupportProvinceResponse*);
    soap_POST_recv__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse*);
    @endcode

  - <ns1:getSupportDataSet> @ref _ns1__getSupportDataSet
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportDataSet(struct soap*, const char *URL, _ns1__getSupportDataSet*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportDataSet(struct soap*, const char *URL, _ns1__getSupportDataSet*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportDataSet(struct soap*, const char *URL, _ns1__getSupportDataSet*);
    soap_POST_recv__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet*);
    @endcode

  - <ns1:getSupportDataSetResponse> @ref _ns1__getSupportDataSetResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getSupportDataSetResponse(struct soap*, const char *URL, _ns1__getSupportDataSetResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getSupportDataSetResponse(struct soap*, const char *URL, _ns1__getSupportDataSetResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getSupportDataSetResponse(struct soap*, const char *URL, _ns1__getSupportDataSetResponse*);
    soap_POST_recv__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse*);
    @endcode

  - <ns1:getWeatherbyCityName> @ref _ns1__getWeatherbyCityName
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getWeatherbyCityName(struct soap*, const char *URL, _ns1__getWeatherbyCityName*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getWeatherbyCityName(struct soap*, const char *URL, _ns1__getWeatherbyCityName*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getWeatherbyCityName(struct soap*, const char *URL, _ns1__getWeatherbyCityName*);
    soap_POST_recv__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName*);
    @endcode

  - <ns1:getWeatherbyCityNameResponse> @ref _ns1__getWeatherbyCityNameResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getWeatherbyCityNameResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getWeatherbyCityNameResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getWeatherbyCityNameResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameResponse*);
    soap_POST_recv__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse*);
    @endcode

  - <ns1:getWeatherbyCityNamePro> @ref _ns1__getWeatherbyCityNamePro
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getWeatherbyCityNamePro(struct soap*, const char *URL, _ns1__getWeatherbyCityNamePro*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getWeatherbyCityNamePro(struct soap*, const char *URL, _ns1__getWeatherbyCityNamePro*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getWeatherbyCityNamePro(struct soap*, const char *URL, _ns1__getWeatherbyCityNamePro*);
    soap_POST_recv__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro*);
    @endcode

  - <ns1:getWeatherbyCityNameProResponse> @ref _ns1__getWeatherbyCityNameProResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getWeatherbyCityNameProResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameProResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getWeatherbyCityNameProResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameProResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getWeatherbyCityNameProResponse(struct soap*, const char *URL, _ns1__getWeatherbyCityNameProResponse*);
    soap_POST_recv__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse*);
    @endcode

  - <ns1:ArrayOfString> (use wsdl2h option -g to auto-generate type _ns1__ArrayOfString)

  - <ns1:DataSet> @ref _ns1__DataSet
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__DataSet(struct soap*, _ns1__DataSet*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__DataSet(struct soap*, _ns1__DataSet*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__DataSet(struct soap*, const char *URL, _ns1__DataSet*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__DataSet(struct soap*, const char *URL, _ns1__DataSet*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__DataSet(struct soap*, const char *URL, _ns1__DataSet*);
    soap_POST_recv__ns1__DataSet(struct soap*, _ns1__DataSet*);
    @endcode

*/

/* End of weatherService.h */
